version: '3.4'

services: 
    db:
      image: postgres
      container_name: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: dev
        POSTGRES_DB: dev
        POSTGRES_PASSWORD: dev
      volumes:
        - pgdata:/var/lib/postgresql/data
    go-api: 
      build:
        context: ./
      ports:
        - 8080:8080
      environment:
        URL: localhost
        PORT: 8080
      depends_on:
      - db

volumes:
  pgdata: