version: '3.4'

networks:
  goNet: 
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.0.0/24

services: 
    db:
      image: postgres
      container_name: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: dev
        POSTGRES_DB: dev
        POSTGRES_PASSWORD: dev
      networks:
        goNet:
          ipv4_address: 172.168.0.5
      volumes:
        - pgdata:/var/lib/postgresql/data
    go-api: 
      build:
        context: ./
      ports:
        - 8080:8080
      environment:
        URL: localhost
        PORT: 8080
      networks:
        goNet:
          ipv4_address: 172.168.0.6
      depends_on:
      - db

volumes:
  pgdata:
